### ISSUE TITLE
MQTT v3.1?

### ISSUE THREAD

**Issue by ghost** [yilun/node_mqtt_client#1]
Would it be possible to make this compatible with IBM v3.1 spec that allows for authentication?

**Comment by yilun** [comment]
hi, man, sorry, i dont have much spare time to do that, i does not like javascript... whats ur project?

**Comment by ghost** [comment]
No worries :)  It was hooking it up with a production broker that was authenticated -- wanted to integrate pub/sub into my node-monitor github project.
